### ISSUE TITLE
error when running the bot

### ISSUE THREAD

**Issue by LunarcatOwO** [LunarcatOwO/iseal-discord-bot#3]
file:///home/ubuntu/iseal-discord-bot/main.js:125
  await rest.put(Routes.applicationCommands(CLIENT_ID), { body: commands });

**Comment by LunarcatOwO** [comment]
file:///home/ubuntu/iseal-discord-bot/main.js:125
  await rest.put(Routes.applicationCommands(CLIENT_ID), { body: commands });
  ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21

**Comment by LunarcatOwO** [comment]
/home/ubuntu/iseal-discord-bot/node_modules/@discordjs/util/dist/index.js:39
  return () => defaultValue ??= cb();
                             ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/ubuntu/iseal-discord-bot/node_modules/discord.js/src/index.js:3:29)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by LunarcatOwO** [comment]
Need to get 0 B/30.7 MB of archives.
After this operation, 194 MB of additional disk space will be used.
(Reading database ... 202625 files and directories currently installed.)
Preparing to unpack .../nodejs_20.13.1-1nodesource1_arm64.deb ...
Unpacking nodejs (20.13.1-1nodesource1) ...
dpkg: error processing archive /var/cache/apt/archives/nodejs_20.13.1-1nodesource1_arm64.deb (--unpack):
 trying to overwrite '/usr/include/node/common.gypi', which is also in package libnode-dev 12.22.9~dfsg-1ubuntu3.5
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/nodejs_20.13.1-1nodesource1_arm64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
